name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i -g npm@latest
      - run: npm ci
      - uses: actions/cache@v2
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-cache-${{ github.sha }}
            ${{ runner.os }}-next-cache-
      - uses: actions/cache@v2
        with:
          path: .next
          key: ${{ runner.os }}-next-build-${{ github.sha }}
      - run: npm run build
